export type AppLanguage = 'pl'

export interface Translations {
  app: {
    title: string
    subtitle: string
    toast: {
      tooFewParticipants: string
      noKeyHolder: string
      scheduleAdded: (count: number, total: number) => string
      scheduleUpdated: (count: number, total: number) => string
      scheduleAddedAndUpdated: (added: number, updated: number, total: number) => string
      scheduleComplete: string
      scheduleError: string
      participantUpdated: string
      participantAdded: string
      participantDeleted: string
      samplesAdded: string
      scheduleAutoGenerated: string
      historicalAdded: string
      manualAdded: string
      manualConflict: string
      shiftDeleted: string
      shiftUpdated: string
      exported: string
      exportError: string
      imported: string
      importError: string
      fileReadError: string
      invalidFile: string
    }
  }
  schedule: {
    title: string
    addHistoricalBtn: string
    addManualBtn: string
    generateBtn: string
    refillBtn: string
    fillMode: {
      label: string
      desc: string
    }
    historical: (count: number) => string
    manual: (count: number) => string
    planned: (count: number) => string
    empty: {
      title: string
      desc: string
    }
    column: {
      no: string
      date: string
      participants: string
      status: string
    }
    status: {
      done: string
      planned: string
      manual: string
    }
    unknown: string
    specialDay: string
    frequency: {
      daily: string
      'every-2-days': string
      'every-3-days': string
      weekly: string
    }
  }
  participants: {
    title: string
    countLabel: (count: number) => string
    addBtn: string
    fillSamplesBtn: string
    empty: string
    keys: string
  }
  dialog: {
    addParticipant: {
      title: string
      editTitle: string
      desc: string
      firstName: string
      lastName: string
      hasKeys: string
      hasKeysDesc: string
      btnAdd: string
      btnSave: string
      btnCancel: string
    }
    addHistorical: {
      title: string
      editTitle: string
      desc: string
      shiftDate: string
      participantsLabel: (count: number) => string
      noParticipants: string
      specialDayLabel: string
      specialDayNone: string
      btnAdd: string
      btnSave: string
      btnCancel: string
    }
    addShift: {
      title: string
      editTitle: string
      desc: string
      shiftDate: string
      participantsLabel: (count: number) => string
      noParticipants: string
      specialDayLabel: string
      specialDayNone: string
      btnAdd: string
      btnSave: string
      btnCancel: string
    }
  }
  settings: {
    title: string
    frequency: string
    peoplePerShift: string
    startDate: string
    endDate: string
    language: string
    backup: {
      title: string
      export: string
      import: string
      importWarning: string
    }
  }
  specialDays: {
    title: string
    none: string
    countLabel: (count: number) => string
    peopleLabel: (count: number) => string
    nameLabel: string
    placeholder: string
    peopleCount: string
    dayOfWeek: string
    addBtn: string
    weekOccurrence: {
      first: string
      second: string
      third: string
      fourth: string
      last: string
    }
    dayName: {
      monday: string
      tuesday: string
      wednesday: string
      thursday: string
      friday: string
    }
    weekOccurrenceField: {
      monday: string
      tuesday: string
      wednesday: string
      thursday: string
      friday: string
    }
  }
  stats: {
    title: string
    total: string
    avg: string
    empty: string
  }
  errorFallback: {
    title: string
    desc: string
    errorDetails: string
    btnRetry: string
  }
}
