import { toast } from 'sonner'
import { Toaster } from '@/components/ui/sonner'
import { useParticipants } from '@/hooks/use-participants'
import { useSettings } from '@/hooks/use-settings'
import { useSchedule } from '@/hooks/use-schedule'
import { useHistoricalShifts } from '@/hooks/use-historical-shifts'
import { useOffDays } from '@/hooks/use-off-days'
import { useParticipantAbsences } from '@/hooks/use-participant-absences'
import { ParticipantsPanel } from '@/components/ParticipantsPanel'
import { SettingsPanel } from '@/components/SettingsPanel'
import { SchedulePanel } from '@/components/SchedulePanel'
import { StatsCard } from '@/components/StatsCard'
import { SpecialDaysManager } from '@/components/SpecialDaysManager'
import { OffDaysManager } from '@/components/OffDaysManager'
import { Participant, Shift, FillMode, OffDay, ParticipantAbsence } from '@/lib/types'
import { exportBackup, parseBackup } from '@/lib/backup'
import { generateScheduleHTML, PrintExportLabels } from '@/lib/print-export'
import { useTranslation } from '@/lib/i18n'

function App() {
  const { t, language, setLanguage, locale } = useTranslation()
  const participantsState = useParticipants()
  const { settings, update: updateSettings, updateSpecialDays, replace: replaceSettings } = useSettings()
  const scheduleState = useSchedule()
  const historyState = useHistoricalShifts()
  const offDaysState = useOffDays()
  const absencesState = useParticipantAbsences()

  const handleGenerate = async (fillMode: FillMode) => {
    const { participants } = participantsState
    if (participants.length < settings.peoplePerShift) {
      toast.error(t.app.toast.tooFewParticipants)
      return
    }
    if (!participants.some((p) => p.hasKeys)) {
      toast.error(t.app.toast.noKeyHolder)
      return
    }
    try {
      const { added, updated, total } = await scheduleState.generate(
        participants,
        settings,
        historyState.historicalShifts,
        fillMode,
        offDaysState.offDays,
        absencesState.absences
      )
      if (added > 0 && updated > 0) {
        toast.success(t.app.toast.scheduleAddedAndUpdated(added, updated, total))
      } else if (added > 0) {
        toast.success(t.app.toast.scheduleAdded(added, total))
      } else if (updated > 0) {
        toast.success(t.app.toast.scheduleUpdated(updated, total))
      } else {
        toast.info(t.app.toast.scheduleComplete)
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : t.app.toast.scheduleError)
    }
  }

  const handleAddOrUpdateParticipant = (participant: Participant) => {
    const isEdit = !!participantsState.editingParticipant
    participantsState.addOrUpdate(participant)
    toast.success(isEdit ? t.app.toast.participantUpdated : t.app.toast.participantAdded)
  }

  const handleDeleteParticipant = (id: string) => {
    participantsState.remove(id)
    absencesState.removeByParticipant(id)
    toast.success(t.app.toast.participantDeleted)
  }

  const handleAddSamples = async () => {
    const result = participantsState.addSampleParticipants()
    toast.success(t.app.toast.samplesAdded)
    if (result.length >= settings.peoplePerShift) {
      try {
        await scheduleState.generate(result, settings, historyState.historicalShifts, 'ignore-existing-positions', offDaysState.offDays, absencesState.absences)
        toast.success(t.app.toast.scheduleAutoGenerated)
      } catch {
        // sample participants were added, schedule generation is optional
      }
    }
  }

  const handleAddAbsence = (absence: ParticipantAbsence) => {
    absencesState.add(absence)
  }

  const handleRemoveAbsence = (id: string) => {
    absencesState.remove(id)
  }

  const handleAddOffDay = (offDay: OffDay): 'ok' | 'conflict' => {
    const occupiedDates = new Set(scheduleState.schedule.map((s) => s.date))
    const result = offDaysState.add(offDay, occupiedDates)
    if (result === 'ok') {
      toast.success(t.app.toast.offDayAdded)
    } else {
      toast.error(t.app.toast.offDayConflict)
    }
    return result
  }

  const handleDeleteOffDay = (id: string) => {
    offDaysState.remove(id)
    toast.success(t.app.toast.offDayDeleted)
  }

  const handleAddHistorical = (shift: Shift) => {
    historyState.add(shift)
    toast.success(t.app.toast.historicalAdded)
  }

  const handleAddShift = (shift: Shift): 'ok' | 'conflict' => {
    const result = scheduleState.add(shift)
    if (result === 'ok') {
      toast.success(t.app.toast.shiftAdded)
    } else {
      toast.error(t.app.toast.shiftConflict)
    }
    return result
  }

  const handleDeleteShift = (id: string, isHistorical: boolean) => {
    if (isHistorical) {
      historyState.remove(id)
    } else {
      scheduleState.removeShift(id)
    }
    toast.success(t.app.toast.shiftDeleted)
  }

  const handleUpdateShift = (id: string, participants: string[], isHistorical: boolean, specialDayId?: string | null) => {
    if (isHistorical) {
      historyState.update(id, participants, specialDayId)
    } else {
      scheduleState.updateShift(id, participants, specialDayId)
    }
    toast.success(t.app.toast.shiftUpdated)
  }

  const handleFillSingleDay = (id: string) => {
    const { participants } = participantsState
    if (participants.length < settings.peoplePerShift) {
      toast.error(t.app.toast.tooFewParticipants)
      return
    }
    if (!participants.some((p) => p.hasKeys)) {
      toast.error(t.app.toast.noKeyHolder)
      return
    }
    const result = scheduleState.fillSingleDay(
      id,
      participants,
      settings,
      historyState.historicalShifts,
      absencesState.absences
    )
    if (result.changed) {
      toast.success(t.app.toast.singleDayFilled)
    } else {
      toast.info(t.app.toast.singleDayAlreadyComplete)
    }
  }

  const handlePrintExport = () => {
    try {
      const labels: PrintExportLabels = {
        pageTitle: t.printExport.labels.pageTitle,
        appTitle: settings.printTitle?.trim() || t.app.title,
        periodLabel: t.printExport.labels.periodLabel,
        noData: t.printExport.labels.noData,
        offDayLabel: t.printExport.labels.offDayLabel,
        column: t.printExport.labels.column,
        keyHolder: t.printExport.labels.keyHolder,
      }
      const html = generateScheduleHTML(
        {
          participants: participantsState.participants,
          settings,
          schedule: scheduleState.schedule,
          historicalShifts: historyState.historicalShifts,
          offDays: offDaysState.offDays,
          participantAbsences: absencesState.absences,
        },
        locale,
        labels
      )
      const win = window.open('', '_blank')
      if (!win) {
        toast.error(t.printExport.toast.error)
        return
      }
      win.document.write(html)
      win.document.close()
      toast.success(t.printExport.toast.success)
    } catch {
      toast.error(t.printExport.toast.error)
    }
  }

  const handleExport = () => {
    try {
      exportBackup({
        participants: participantsState.participants,
        settings,
        schedule: scheduleState.schedule,
        historicalShifts: historyState.historicalShifts,
        offDays: offDaysState.offDays,
        participantAbsences: absencesState.absences,
      })
      toast.success(t.app.toast.exported)
    } catch {
      toast.error(t.app.toast.exportError)
    }
  }

  const handleImport = (file: File) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      try {
        const raw = e.target?.result
        if (typeof raw !== 'string') throw new Error(t.app.toast.invalidFile)
        const appData = parseBackup(raw)
        participantsState.replace(appData.participants)
        replaceSettings(appData.settings)
        scheduleState.replace(appData.schedule)
        historyState.replace(appData.historicalShifts)
        offDaysState.replace(appData.offDays)
        absencesState.replace(appData.participantAbsences)
        toast.success(t.app.toast.imported)
      } catch (err) {
        toast.error(err instanceof Error ? err.message : t.app.toast.importError)
      }
    }
    reader.onerror = () => {
      toast.error(t.app.toast.fileReadError)
    }
    reader.readAsText(file)
  }

  return (
    <>
      <Toaster />
      <div className="min-h-screen bg-background p-4 md:p-8">
        <div className="mx-auto max-w-7xl">
          <header className="mb-8">
            <h1 className="text-4xl font-bold tracking-tight text-foreground">
              {t.app.title}
            </h1>
            <p className="mt-2 text-muted-foreground">
              {t.app.subtitle}
            </p>
          </header>

          <div className="flex flex-col gap-6 lg:flex-row">
            <div className="flex flex-col gap-6 lg:w-1/3">
              <ParticipantsPanel
                participants={participantsState.participants}
                dialogOpen={participantsState.dialogOpen}
                editingParticipant={participantsState.editingParticipant}
                absences={absencesState.absences}
                onOpenAdd={participantsState.openAdd}
                onOpenEdit={participantsState.openEdit}
                onCloseDialog={(open) => {
                  participantsState.setDialogOpen(open)
                  if (!open) participantsState.closeDialog()
                }}
                onAddOrUpdate={handleAddOrUpdateParticipant}
                onDelete={handleDeleteParticipant}
                onAddSamples={handleAddSamples}
                onAddAbsence={handleAddAbsence}
                onRemoveAbsence={handleRemoveAbsence}
              />

              <SettingsPanel
                settings={settings}
                maxPeople={participantsState.participants.length}
                language={language}
                onUpdate={updateSettings}
                onLanguageChange={setLanguage}
                onExport={handleExport}
                onImport={handleImport}
              />

              <SpecialDaysManager
                specialDays={settings.specialDays || []}
                onUpdate={updateSpecialDays}
                maxPeoplePerShift={participantsState.participants.length || 10}
              />

              <OffDaysManager
                offDays={offDaysState.offDays}
                onAdd={handleAddOffDay}
                onRemove={handleDeleteOffDay}
                occupiedDates={new Set(scheduleState.schedule.map((s) => s.date))}
              />
            </div>

            <div className="flex-1 flex flex-col gap-6">
              <StatsCard
                participants={participantsState.participants}
                schedule={scheduleState.schedule}
                historicalShifts={historyState.historicalShifts}
              />

              <SchedulePanel
                participants={participantsState.participants}
                schedule={scheduleState.schedule}
                historicalShifts={historyState.historicalShifts}
                offDays={offDaysState.offDays}
                settings={settings}
                isGenerating={scheduleState.isGenerating}
                historicalDialogOpen={historyState.dialogOpen}
                shiftDialogOpen={scheduleState.shiftDialogOpen}
                onGenerate={handleGenerate}
                onDeleteShift={handleDeleteShift}
                onDeleteOffDay={handleDeleteOffDay}
                onUpdateShift={handleUpdateShift}
                onAddHistorical={handleAddHistorical}
                onAddShift={handleAddShift}
                onHistoricalDialogChange={historyState.setDialogOpen}
                onShiftDialogChange={scheduleState.setShiftDialogOpen}
                onFillSingleDay={handleFillSingleDay}
                onPrintExport={handlePrintExport}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default App
