import { toast } from 'sonner'
import { Toaster } from '@/components/ui/sonner'
import { useParticipants } from '@/hooks/use-participants'
import { useSettings } from '@/hooks/use-settings'
import { useSchedule } from '@/hooks/use-schedule'
import { useHistoricalShifts } from '@/hooks/use-historical-shifts'
import { ParticipantsPanel } from '@/components/ParticipantsPanel'
import { SettingsPanel } from '@/components/SettingsPanel'
import { SchedulePanel } from '@/components/SchedulePanel'
import { StatsCard } from '@/components/StatsCard'
import { SpecialDaysManager } from '@/components/SpecialDaysManager'
import { Participant, Shift } from '@/lib/types'
import { exportBackup, parseBackup } from '@/lib/backup'
import { useTranslation } from '@/lib/i18n'

function App() {
  const { t, language, setLanguage } = useTranslation()
  const participantsState = useParticipants()
  const { settings, update: updateSettings, updateSpecialDays, replace: replaceSettings } = useSettings()
  const scheduleState = useSchedule()
  const historyState = useHistoricalShifts()

  const handleGenerate = async () => {
    const { participants } = participantsState
    if (participants.length < settings.peoplePerShift) {
      toast.error(t.app.toast.tooFewParticipants)
      return
    }
    if (!participants.some((p) => p.hasKeys)) {
      toast.error(t.app.toast.noKeyHolder)
      return
    }
    try {
      const { added, total } = await scheduleState.generate(
        participants,
        settings,
        historyState.historicalShifts
      )
      if (added > 0) {
        toast.success(t.app.toast.scheduleAdded(added, total))
      } else {
        toast.info(t.app.toast.scheduleComplete)
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : t.app.toast.scheduleError)
    }
  }

  const handleAddOrUpdateParticipant = (participant: Participant) => {
    const isEdit = !!participantsState.editingParticipant
    participantsState.addOrUpdate(participant)
    toast.success(isEdit ? t.app.toast.participantUpdated : t.app.toast.participantAdded)
  }

  const handleDeleteParticipant = (id: string) => {
    participantsState.remove(id)
    toast.success(t.app.toast.participantDeleted)
  }

  const handleAddSamples = async () => {
    const result = participantsState.addSampleParticipants()
    toast.success(t.app.toast.samplesAdded)
    if (result.length >= settings.peoplePerShift) {
      try {
        await scheduleState.generate(result, settings, historyState.historicalShifts)
        toast.success(t.app.toast.scheduleAutoGenerated)
      } catch {
        // sample participants were added, schedule generation is optional
      }
    }
  }

  const handleAddHistorical = (shift: Shift) => {
    historyState.add(shift)
    toast.success(t.app.toast.historicalAdded)
  }

  const handleDeleteShift = (id: string, isHistorical: boolean) => {
    if (isHistorical) {
      historyState.remove(id)
    } else {
      scheduleState.removeShift(id)
    }
    toast.success(t.app.toast.shiftDeleted)
  }

  const handleExport = () => {
    try {
      exportBackup({
        participants: participantsState.participants,
        settings,
        schedule: scheduleState.schedule,
        historicalShifts: historyState.historicalShifts,
      })
      toast.success(t.app.toast.exported)
    } catch {
      toast.error(t.app.toast.exportError)
    }
  }

  const handleImport = (file: File) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      try {
        const raw = e.target?.result
        if (typeof raw !== 'string') throw new Error(t.app.toast.invalidFile)
        const appData = parseBackup(raw)
        participantsState.replace(appData.participants)
        replaceSettings(appData.settings)
        scheduleState.replace(appData.schedule)
        historyState.replace(appData.historicalShifts)
        toast.success(t.app.toast.imported)
      } catch (err) {
        toast.error(err instanceof Error ? err.message : t.app.toast.importError)
      }
    }
    reader.onerror = () => {
      toast.error(t.app.toast.fileReadError)
    }
    reader.readAsText(file)
  }

  return (
    <>
      <Toaster />
      <div className="min-h-screen bg-background p-4 md:p-8">
        <div className="mx-auto max-w-7xl">
          <header className="mb-8">
            <h1 className="text-4xl font-bold tracking-tight text-foreground">
              {t.app.title}
            </h1>
            <p className="mt-2 text-muted-foreground">
              {t.app.subtitle}
            </p>
          </header>

          <div className="flex flex-col gap-6 lg:flex-row">
            <div className="flex flex-col gap-6 lg:w-1/3">
              <ParticipantsPanel
                participants={participantsState.participants}
                dialogOpen={participantsState.dialogOpen}
                editingParticipant={participantsState.editingParticipant}
                onOpenAdd={participantsState.openAdd}
                onOpenEdit={participantsState.openEdit}
                onCloseDialog={(open) => {
                  participantsState.setDialogOpen(open)
                  if (!open) participantsState.closeDialog()
                }}
                onAddOrUpdate={handleAddOrUpdateParticipant}
                onDelete={handleDeleteParticipant}
                onAddSamples={handleAddSamples}
              />

              <SettingsPanel
                settings={settings}
                maxPeople={participantsState.participants.length}
                language={language}
                onUpdate={updateSettings}
                onLanguageChange={setLanguage}
                onExport={handleExport}
                onImport={handleImport}
              />

              <SpecialDaysManager
                specialDays={settings.specialDays || []}
                onUpdate={updateSpecialDays}
                maxPeoplePerShift={participantsState.participants.length || 10}
              />
            </div>

            <div className="flex-1 flex flex-col gap-6">
              <StatsCard
                participants={participantsState.participants}
                schedule={scheduleState.schedule}
                historicalShifts={historyState.historicalShifts}
              />

              <SchedulePanel
                participants={participantsState.participants}
                schedule={scheduleState.schedule}
                historicalShifts={historyState.historicalShifts}
                settings={settings}
                isGenerating={scheduleState.isGenerating}
                historicalDialogOpen={historyState.dialogOpen}
                onGenerate={handleGenerate}
                onDeleteShift={handleDeleteShift}
                onAddHistorical={handleAddHistorical}
                onHistoricalDialogChange={historyState.setDialogOpen}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default App
